name: wakelock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.
version: 0.6.2
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock

publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.2.0

  wakelock_macos: 
    git:
      url: https://github.com/MuksithMRA/wakelock-plus.git
      path: wakelock_macos/
  wakelock_platform_interface: 
    git:
      url: https://github.com/MuksithMRA/wakelock-plus.git
      path: wakelock_platform_interface/
  wakelock_web: 
    git:
      url: https://github.com/MuksithMRA/wakelock-plus.git
      path: wakelock_web/
  wakelock_windows: 
    git:
      url: https://github.com/MuksithMRA/wakelock-plus.git
      path: wakelock_windows/

dev_dependencies:
  flutter_lints: ^1.0.4
  pigeon: ^1.0.2 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
      macos:
        default_package: wakelock_macos
      windows:
        default_package: wakelock_windows
      web:
        default_package: wakelock_web
